[deploy]
# Information about the target OS

# iptables config location
nftables = "/etc/nftables/nftables.conf"

[firewall]
# firewall configuration

    [firewall.lan]
    # LAN information

    # LAN interface
    if = "eth0"
    # Network ID and CIDR
    id = ""
    cidr = ""
    # IP of default gateway
    gateway = ""

    [firewall.qz]
    # QZ information

    # Quarantine interface
    if = "eth1"
    # Quarantined host
    host = ""