[filesystem]
# Filesystem configuration

# Full path to mount point from /
# e.g. /mnt/smallwall
mountpoint = "/mnt/smallwall"

# Full path to nftables.conf from external disk root
# e.g. /etc/nftables.conf
nftables = "/etc/nftables.conf"

[firewall]
# Firewall configuration

    [firewall.lan]
    # LAN configuration

    # Physical interface
    interface = "eth0"

    # Network ID and CIDR
    network_id = "192.168.1.0"
    cidr = "/24"

    # IP of default gateway
    gateway = "192.168.1.1"

    [firewall.qz]
    # QZ configuration

    # Physical interface
    interface = "eth1"

    # Quarantined host IP
    host_ip = ""